name: fastp ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "./src"
          exclude: "./lib"
          extensions: "h,hpp,cpp,c"
          clangFormatVersion: 10
          inplace: False
  build:
    needs: code-lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout scm
        uses: actions/checkout@v2
      - name: install build dependencies (Linux)
        run: sudo apt update && sudo apt install -y build-essential nasm
        if: runner.os == 'Linux'
      - name: install build dependencies (MacOS)
        run: brew install automake autoconf coreutils nasm
        if: runner.os == 'macOS'
      - name: get deflate
        uses: actions/checkout@v2
        with:
          repository: https://github.com/ebiggers/libdeflate.git
          path: fastp/src/libs/deflate
      - name: build deflate
        run: |
          cd src/libs/deflate
          bash -c 'make -j $(nproc)'
          sudo make install
          cd -
      - name: get isa-l
        uses: actions/checkout@v2
        with:
          repository: https://github.com/intel/isa-l.git
          path: fastp/src/libs/isa-l
      - name: build isa-l
        run: |
          cd src/libs/isa-l
          ./autogen.sh
          ./configure --prefix=/usr --libdir=/usr/lib64
          bash -c 'make -j $(nproc)'
          sudo make install
          cd -
      - name: make fatsp
        run: bash -c 'make -j $(nproc) static'
      - name: test
        run: chmod a+x ./fastp && ./fastp --version
